import { GetStaticPaths, GetStaticProps } from "next";
import { ParsedUrlQuery } from "querystring";
import data from "../../../books.json";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

interface IParams extends ParsedUrlQuery {
  bookName: string;
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { bookName } = context.params as IParams;
  // get all the chapters from the book named bookName
  const book = data.find((book) => book.name.replace(" ", "") === bookName);
  if (book) {
    const chapters = book.chapters;
    const chapterNumbers = chapters.map((chapter) => chapter.number);
    return {
      props: {
        bookName: book.name,
        chapterNumbers: chapterNumbers,
      },
    };
  }

  return {
    props: {},
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  //get all the bookNames from data
  const books = data;
  const paths = books.map((book) => ({
    params: {
      bookName: book.name.replace(" ", ""),
    },
  }));
  return {
    paths: paths.flat(),
    fallback: true,
  };
};

const Chapters = ({
  bookName,
  chapterNumbers,
}: {
  bookName: string;
  chapterNumbers: number[];
}) => {
  return (
    <>
      <Head>
        <title>Chapters | Copy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex cursor-pointer flex-row items-center pl-8 pt-4 font-semibold uppercase text-gray-600">
        <Link className="hover:text-blue-500" href={"/"}>
          Book of Mormon
        </Link>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 20 20"
          fill="currentColor"
          className="h-5 w-5"
        >
          <path
            fillRule="evenodd"
            d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
            clipRule="evenodd"
          />
        </svg>
        <Link className="hover:text-blue-500" href={"/book_of_mormon"}>
          {bookName}
        </Link>
      </div>
      <main className="mt-4 mb-10 flex flex-col items-center bg-[conic-gradient(at_bottom_right,_var(--tw-gradient-stops))] from-stone-300 via-pink-500 to-blue-500 bg-clip-text">
        {chapterNumbers &&
          chapterNumbers.map((chapterNumber) => {
            return (
              <Link
                key={chapterNumber}
                className="text-xl font-semibold uppercase text-transparent hover:text-blue-500"
                href={`/book_of_mormon/${bookName.replace(
                  " ",
                  ""
                )}/${chapterNumber}`}
              >
                Chapter {chapterNumber}
              </Link>
            );
          })}
      </main>
    </>
  );
};

export default Chapters;
