import { GetStaticPaths, GetStaticProps } from "next";
import { ParsedUrlQuery } from "querystring";
import data from "../../../books.json";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

interface IParams extends ParsedUrlQuery {
  bookName: string;
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { bookName } = context.params as IParams;
  // get all the chapters from the book named bookName
  const book = data.find((book) => book.name.replace(" ", "") === bookName);
  if (book) {
    const chapters = book.chapters;
    const chapterNumbers = chapters.map((chapter) => chapter.number);
    return {
      props: {
        bookName: book.name,
        chapterNumbers: chapterNumbers,
      },
    };
  }

  return {
    props: {},
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [{ params: { bookName: "1Nephi" } }],
    fallback: true,
  };
};

const Chapters = ({
  bookName,
  chapterNumbers,
}: {
  bookName: string;
  chapterNumbers: number[];
}) => {
  return (
    <>
      <Head>
        <title>Chapters | Copy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="cursor-pointer pl-8 pt-4 font-[Garamound] font-semibold uppercase text-gray-600">
        <Link className="hover:text-blue-500" href={"/"}>
          Book of Mormon
        </Link>
        {" >"}{" "}
        <Link className="hover:text-blue-500" href={"/book_of_mormon"}>
          1 Nephi
        </Link>
      </div>
      <main className="mt-4 flex flex-col items-center font-[Garamound]">
        {chapterNumbers &&
          chapterNumbers.map((chapterNumber) => {
            return (
              <Link
                key={chapterNumber}
                className="text-xl font-semibold uppercase hover:text-blue-500"
                href={`/book_of_mormon/${bookName.replace(
                  " ",
                  ""
                )}/${chapterNumber}`}
              >
                Chapter {chapterNumber}
              </Link>
            );
          })}
      </main>
    </>
  );
};

export default Chapters;
